<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_flower
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

// Include Request SDK
include_once AKPATH_COMPONENT.'/api/request/item.php' ;
include_once AKPATH_COMPONENT.'/api/request/list.php' ;

include_once dirname(__FILE__).'/sdk.php' ;

// Init SDK
$params = JComponentHelper::getParams('com_flower') ;

$host = $params->get('ApiSystem_Host') ;

AKHelper::_('system.getApiSDK', $host) ;