#!/bin/sh

SITE="joomla310"
COM="flower"
MOD="flower"
PLG="flower"
GUP="system"


rm ../com_$COM.zip

# admin
rm -rf admin
mkdir admin
cp -rf /var/www/$SITE/administrator/components/com_$COM/ admin
echo "Admin copied" ;

# site
rm -rf site
mkdir site
cp -rf /var/www/$SITE/components/com_$COM/ site
echo "Site copied" ;

# library
rm -rf admin/windwalker
mkdir admin/windwalker
cp -rf /var/www/$SITE/libraries/windwalker/ admin/windwalker
rm -rf admin/windwalker/.git
rm -f admin/windwalker/.gitignore
echo "Lib copied" ;

# Set Template
rm -rf tmpl/component
mkdir -p tmpl/component

cp -rf admin/ tmpl/component/init.administrator

mkdir tmpl/component/subsystem.administrator
mv tmpl/component/init.administrator/controllers tmpl/component/subsystem.administrator
mv tmpl/component/init.administrator/models tmpl/component/subsystem.administrator
mv tmpl/component/init.administrator/views tmpl/component/subsystem.administrator
mv tmpl/component/init.administrator/tables tmpl/component/subsystem.administrator
mv tmpl/component/init.administrator/sql tmpl/component/subsystem.administrator
mv tmpl/component/init.administrator/images tmpl/component/subsystem.administrator


cp -rf site/ tmpl/component/init.site

mkdir tmpl/component/subsystem.site
mv tmpl/component/init.site/controllers tmpl/component/subsystem.site
mv tmpl/component/init.site/models tmpl/component/subsystem.site
mv tmpl/component/init.site/views tmpl/component/subsystem.site
mv tmpl/component/init.site/sql tmpl/component/subsystem.site


# xml and install script
# cp -f /var/www/$SITE/administrator/components/com_$COM/$COM.xml .
# echo "Component XML copied" ;

# cp -f /var/www/$SITE/administrator/components/com_$COM/install.php .
# echo "Component install scrip copied" ;

# modules site
# rm -rf modules
# mkdir modules
# cp -rf /var/www/$SITE/modules/mod_$MOD/ modules/mod_$MOD
# echo "Module copied" ;

# modules admin
# rm -rf modules
# mkdir modules
# cp -rf /var/www/$SITE/administrator/modules/mod_$MOD/ modules/mod_$MOD
# echo "Module copied" ;

# plugins
# rm -rf plugins
# mkdir plugins
# cp -rf /var/www/$SITE/plugins/$GUP/$PLG/ plugins/plg_$GUP\_$PLG
# echo "Plugin copied" ;


git add .
echo "Execute git add" ;

zip -rq ../com_$COM.zip *
echo "Ziped files" ;


exit 0
