<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_flower
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;

/**
 * flowerLoader
 *
 * @param $uri
 *
 * @return mixed
 */
function flowerLoader($uri)
{
	return FlowerHelper::_('loader.import', $uri);
}
